balanceMessageTemplate: Current balance is %s

bank1BalancePath: http://localhost:8080/balances/ext/bank1/{name}

bank2BalancePath: http://localhost:8080/balances/ext/bank2/{name}

logging:

  level: INFO

  appenders:
      - type: console
      - type: file
        threshold: INFO
        logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
        currentLogFilename: ./log/balance-service.log
        archivedLogFilenamePattern: ./log/balance-service-%d.log.gz
        archivedFileCount: 7
        timeZone: UTC

views:
  .ftl:
    strict_syntax: yes

metrics:
  type: graphite
  frequency: 10s